
//Sensor actions
export const GET_SENSORS_START     = 'GET_SENSORS_START';
export const GET_SENSORS_SUCCESS   = 'GET_SENSORS_SUCCESS';
export const GET_SENSORS_ERROR     = 'GET_SENSORS_ERROR';
export const CREATE_SENSOR_START   = 'CREATE_SENSOR_START';
export const CREATE_SENSOR_SUCCESS = 'CREATE_SENSOR_SUCCESS';
export const CREATE_SENSOR_ERROR   = 'CREATE_SENSOR_ERROR';
export const DELETE_SENSOR_START   = 'DELETE_SENSOR_START';
export const DELETE_SENSOR_SUCCESS = 'DELETE_SENSOR_SUCCESS';
export const DELETE_SENSOR_ERROR   = 'DELETE_SENSOR_ERROR';
export const UPDATE_SENSOR_START   = 'UPDATE_SENSOR_START';
export const UPDATE_SENSOR_SUCCESS = 'UPDATE_SENSOR_SUCCESS';
export const UPDATE_SENSOR_ERROR   = 'UPDATE_SENSOR_ERROR';

//Users actions
export const GET_USERS_START     = 'GET_USERS_START';
export const GET_USERS_SUCCESS   = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR     = 'GET_USERS_ERROR';
export const CREATE_USER_START   = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR   = 'CREATE_USER_ERROR';
export const UPDATE_USER_START   = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR   = 'UPDATE_USER_ERROR';
export const DELETE_USER_START   = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR   = 'DELETE_USER_ERROR';

//Notif actions
export const GET_NOTIFS_START     = 'GET_NOTIFS_START';
export const GET_NOTIFS_SUCCESS   = 'GET_NOTIFS_SUCCESS';
export const GET_NOTIFS_ERROR     = 'GET_NOTIFS_ERROR';
export const CREATE_NOTIF_START   = 'CREATE_NOTIF_START';
export const CREATE_NOTIF_SUCCESS = 'CREATE_NOTIF_SUCCESS';
export const CREATE_NOTIF_ERROR   = 'CREATE_NOTIF_ERROR';
export const DELETE_NOTIF_START   = 'DELETE_NOTIF_START';
export const DELETE_NOTIF_SUCCESS = 'DELETE_NOTIF_SUCCESS';
export const DELETE_NOTIF_ERROR   = 'DELETE_NOTIF_ERROR';
export const UPDATE_NOTIF_START   = 'UPDATE_NOTIF_START';
export const UPDATE_NOTIF_SUCCESS = 'UPDATE_NOTIF_SUCCESS';
export const UPDATE_NOTIF_ERROR   = 'UPDATE_NOTIF_ERROR';

//Messages
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
