
// Device actions
export const GET_DEVICES_START = 'GET_DEVICES_START';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const GET_DEVICES_ERROR = 'GET_DEVICES_ERROR';
export const GET_DEVICE_ATTRIBUTES_START = 'GET_DEVICES_ATTRIBUTES_START';
export const GET_DEVICE_ATTRIBUTES_SUCCESS = 'GET_DEVICES_ATTRIBUTES_SUCCESS';
export const GET_DEVICE_ATTRIBUTES_ERROR = 'GET_DEVICES_ATTRIBUTES_ERROR';
export const GET_DEVICE_START = 'GET_DEVICE_START';
export const GET_DEVICE_SUCCESS = 'GET_DEVICE_SUCCESS';
export const GET_DEVICE_ERROR = 'GET_DEVICE_ERROR';
export const CREATE_DEVICE_START = 'CREATE_DEVICE_START';
export const CREATE_DEVICE_SUCCESS = 'CREATE_DEVICE_SUCCESS';
export const CREATE_DEVICE_ERROR = 'CREATE_DEVICE_ERROR';
export const DELETE_DEVICE_START = 'DELETE_DEVICE_START';
export const DELETE_DEVICE_SUCCESS = 'DELETE_DEVICE_SUCCESS';
export const DELETE_DEVICE_ERROR = 'DELETE_DEVICE_ERROR';
export const UPDATE_DEVICE_START = 'UPDATE_DEVICE_START';
export const UPDATE_DEVICE_SUCCESS = 'UPDATE_DEVICE_SUCCESS';
export const UPDATE_DEVICE_ERROR = 'UPDATE_DEVICE_ERROR';

// Device actions
export const GET_VALUES_START = 'GET_VALUES_START';
export const GET_VALUES_SUCCESS = 'GET_VALUES_SUCCESS';
export const GET_VALUES_ERROR = 'GET_VALUES_ERROR';

// Users actions
export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

// Notif actions
export const GET_NOTIFS_START = 'GET_NOTIFS_START';
export const GET_NOTIFS_SUCCESS = 'GET_NOTIFS_SUCCESS';
export const GET_NOTIFS_ERROR = 'GET_NOTIFS_ERROR';
export const CREATE_NOTIF_START = 'CREATE_NOTIF_START';
export const CREATE_NOTIF_SUCCESS = 'CREATE_NOTIF_SUCCESS';
export const CREATE_NOTIF_ERROR = 'CREATE_NOTIF_ERROR';
export const DELETE_NOTIF_START = 'DELETE_NOTIF_START';
export const DELETE_NOTIF_SUCCESS = 'DELETE_NOTIF_SUCCESS';
export const DELETE_NOTIF_ERROR = 'DELETE_NOTIF_ERROR';
export const UPDATE_NOTIF_START = 'UPDATE_NOTIF_START';
export const UPDATE_NOTIF_SUCCESS = 'UPDATE_NOTIF_SUCCESS';
export const UPDATE_NOTIF_ERROR = 'UPDATE_NOTIF_ERROR';

// Messages
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

// Permissions
export const GET_PERMS_START = 'GET_PERMS_START';
export const GET_PERMS_SUCCESS = 'GET_PERMS_SUCCESS';
export const GET_PERMS_ERROR = 'GET_PERMS_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';
